[licenses]
private = { ignore = true }
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MIT-0",
  "OFL-1.1",
  "OpenSSL",
  "Ubuntu-font-1.0",
  "Unicode-3.0",
  "Zlib",
]

[advisories]
version = 2
ignore = [
  "RUSTSEC-2024-0436",
  "RUSTSEC-2025-0134",
  "RUSTSEC-2024-0384",
  "RUSTSEC-2025-0141",
]

[bans]
skip-tree = ["bevy"]
# TODO: Update dependencies to avoid duplicates.
skip = [
  "socket2",
  "tungstenite",
  "tokio-tungstenite",
  "hyper",
  "http-body",
  "http",
  "h2",
  "base64",
]
